Add random color functionality
crimsobot/crimsoBOT pull request #158
Opened 2024-05-15 02:25 UTC by korbosoft

gonna test this now

2024-05-15 20:01 UTC, korbosoft commented
should be ready now

2024-05-15 20:14 UTC, h-anjru requested changes

2024-05-15 20:14 UTC, h-anjru commented on crimsobot/cogs/utilities.py
> +        if hex_value is None:
Need whitespace here.

2024-05-15 20:14 UTC, h-anjru commented on crimsobot/cogs/utilities.py
> +        print(str(hex_value))
Need to nix this print(); don't want it clogging up the terminal.

2024-05-16 03:04 UTC, h-anjru approved these changes

2024-05-16 03:07 UTC, h-anjru approved these changes

2024-05-16 03:10 UTC, h-anjru requested changes
Whitespace line 175. Run flake8 before next commit.

2024-05-16 03:25 UTC, h-anjru approved these changes

2024-05-16 03:28 UTC, merged