CRINGO! bugfix & changes
crimsobot/crimsoBOT pull request #99
Opened 2020-09-27 06:38 UTC by kaylynn234

This PR:
- Fixes that darn old nasty NoneCRINGO bug... By turning it into a feature! If someone gets unlucky, well, no coin for them! Watch out for NoneCRINGO!
- Makes coin winnings display on leaderboard.
- Moves some things to f-strings.
- Annihilates this one weird while loop.
- Do you care about the fact that I renamed a few internal variables? Let me know.

2020-09-27 06:49 UTC, williammck requested changes

2020-09-27 06:49 UTC, williammck commented on crimsobot/cogs/cringo.py
> +        game_is_cursed = name_prefix == 'None'
would rather have this be at the top instead of comparing strings...
i.e. `game_is_cursed` is the source of truth on whether we're doing NoneCRINGO

2020-09-27 06:49 UTC, williammck commented on crimsobot/utils/cringo.py
> +        coin_display = 'zero' if cursed else round(line[1] / nerf, 1)  # y'all dumb motherfuckers want a rounding error?
feels weird that we're recalculating this later when we actually grant them the money. for consistency's sake i'd rather refactor `cringo_main` and `cringo_scoreboard` to use a list of NamedTuples or something that we can pass around with all the results/winnings for a particular user.
i know it's super duper not important for something like this, but 🤷🏻‍♂️

2020-09-27 20:28 UTC, williammck requested changes

2020-09-27 20:28 UTC, williammck commented on crimsobot/cogs/cringo.py
> +        game_is_cursed = not CRINGO_RULES['name'][card_size] and random.random() > 0.98
```suggestion
        name_prefix = CRINGO_RULES['name'][card_size]
        game_is_cursed = not name_prefix and random.random() > 0.98
        if game_is_cursed:
            name_prefix = 'None'
```
i think we ended up back in `NoneCRINGO` bug here... does this make sense?

2020-09-27 20:28 UTC, williammck commented on crimsobot/cogs/cringo.py
> +            sorted_players = sorted(list_of_players, key=lambda item: item.score, reverse=True)
why did the sorting move out of `cringo_scoreboard`? imo that's just unnecessary duplication now... same comment applies on L193

2020-09-27 20:28 UTC, williammck commented on crimsobot/utils/cringo.py
> +        coin_display = 'zero' if cursed else player.winnings  # y'all dumb motherfuckers want a rounding error?
lol this comment no longer applies here

2020-09-27 20:28 UTC, williammck commented on crimsobot/cogs/cringo.py
> +                await cringo.cringo_stats(player, index == 0)  # first in sorted list == most score
nice change here :)

2020-09-27 20:28 UTC, williammck commented on crimsobot/cogs/cringo.py
> +            player.winnings = 0 if game_is_cursed else round(player.score / nerf, 1)
so previously we were depositing the full value, now it's just to one decimal point.
i'm fine with this but wanted to call it out.

2020-09-29 01:38 UTC, kaylynn234 commented
Closing this and will open a new PR later. I want to refactor a large portion of this code instead of blindly flailing to fix it and as such the changes I want to make are out of scope for this PR.

2020-09-29 01:38 UTC, closed without merging